# -*- coding: utf-8 -*-
"""Student-managment-systemproject7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uxnDjWfyjujlKSUO_VHVEd_C3FIbWyHA
"""

# Week 7 Project: Student Management System

class StudentManagementSystem:

    # Constructor
    def __init__(self):
        self.students = []

    # Add a new student
    def add_student(self):
        print("\n===== ADD STUDENT =====")

        student_id = input("Enter student ID: ").strip()
        name = input("Enter student name: ").strip().title()
        age = input("Enter student age: ").strip()
        course = input("Enter course name: ").strip().title()

        # Check empty information
        if student_id == "" or name == "" or age == "" or course == "":
            print("All information is required.")
            return

        # Check duplicate student ID
        for student in self.students:
            if student["id"] == student_id:
                print("This student ID already exists.")
                return

        # Create one student record
        student = {
            "id": student_id,
            "name": name,
            "age": age,
            "course": course
        }

        self.students.append(student)
        print("Student added successfully.")

    # Update an existing student
    def update_student(self):
        print("\n===== UPDATE STUDENT =====")

        if len(self.students) == 0:
            print("No student records are available.")
            return

        student_id = input("Enter student ID to update: ").strip()

        for student in self.students:
            if student["id"] == student_id:
                print("Student found:", student["name"])

                new_name = input("Enter new name: ").strip().title()
                new_age = input("Enter new age: ").strip()
                new_course = input("Enter new course: ").strip().title()

                if new_name == "" or new_age == "" or new_course == "":
                    print("New information cannot be empty.")
                    return

                student["name"] = new_name
                student["age"] = new_age
                student["course"] = new_course

                print("Student updated successfully.")
                return

        print("Student ID was not found.")

    # Display all students
    def view_students(self):
        print("\n===== ALL STUDENTS =====")

        if len(self.students) == 0:
            print("No student records are available.")
            return

        for student in self.students:
            print("\nStudent ID:", student["id"])
            print("Name:", student["name"])
            print("Age:", student["age"])
            print("Course:", student["course"])

## Create the Object and Run the Student Menu

# Create an object of the class
system = StudentManagementSystem()

# Main menu
while True:
    print("\n===== STUDENT MANAGEMENT SYSTEM =====")
    print("1. Add Student")
    print("2. Update Student")
    print("3. View All Students")
    print("4. Exit")

    choice = input("Enter your choice: ").strip()

    if choice == "1":
        system.add_student()

    elif choice == "2":
        system.update_student()

    elif choice == "3":
        system.view_students()

    elif choice == "4":
        print("Student Management System closed.")
        break

    else:
        print("Invalid choice. Enter 1, 2, 3, or 4.")

## Testing Results and Conclusion
#The Student Management System was tested successfully